import { User, Project, Task } from './types';

// ユーザーのモックデータ
export const mockUsers: User[] = [
  {
    id: '1',
    name: '山田太郎',
    email: 'yamada@example.com',
    avatar: 'https://i.pravatar.cc/150?img=12',
    role: 'admin',
    bio: 'プロジェクトマネージャー。チーム全体の統括を担当しています。',
    phone: '090-1234-5678',
    status: 'active',
  },
  {
    id: '2',
    name: '佐藤花子',
    email: 'sato@example.com',
    avatar: 'https://i.pravatar.cc/150?img=45',
    role: 'admin',
    bio: 'シニアエンジニア。技術的なリードを担当。',
    phone: '090-2345-6789',
    status: 'active',
  },
  {
    id: '3',
    name: '鈴木一郎',
    email: 'suzuki@example.com',
    avatar: 'https://i.pravatar.cc/150?img=33',
    role: 'member',
    bio: 'フロントエンド開発者。React/TypeScriptが得意です。',
    phone: '090-3456-7890',
    status: 'active',
  },
  {
    id: '4',
    name: '田中美咲',
    email: 'tanaka@example.com',
    avatar: 'https://i.pravatar.cc/150?img=47',
    role: 'member',
    bio: 'バックエンド開発者。API設計が専門。',
    phone: '090-4567-8901',
    status: 'away',
  },
  {
    id: '5',
    name: '高橋健太',
    email: 'takahashi@example.com',
    avatar: 'https://i.pravatar.cc/150?img=52',
    role: 'member',
    bio: 'UIデザイナー。ユーザー体験の向上に注力しています。',
    phone: '090-5678-9012',
    status: 'active',
  },
  {
    id: '6',
    name: '伊藤真理',
    email: 'ito@example.com',
    avatar: 'https://i.pravatar.cc/150?img=31',
    role: 'member',
    bio: 'QAエンジニア。品質保証を担当。',
    phone: '090-6789-0123',
    status: 'active',
  },
  {
    id: '7',
    name: '渡辺直樹',
    email: 'watanabe@example.com',
    avatar: 'https://i.pravatar.cc/150?img=14',
    role: 'member',
    bio: 'DevOpsエンジニア。インフラ構築が得意。',
    phone: '090-7890-1234',
    status: 'offline',
  },
  {
    id: '8',
    name: '中村さくら',
    email: 'nakamura@example.com',
    avatar: 'https://i.pravatar.cc/150?img=48',
    role: 'guest',
    bio: 'インターン生。フロントエンド開発を学習中。',
    status: 'active',
  },
  {
    id: '9',
    name: '小林優斗',
    email: 'kobayashi@example.com',
    avatar: 'https://i.pravatar.cc/150?img=58',
    role: 'member',
    bio: 'データエンジニア。データ分析基盤の構築を担当。',
    phone: '090-8901-2345',
    status: 'active',
  },
  {
    id: '10',
    name: '加藤美優',
    email: 'kato@example.com',
    avatar: 'https://i.pravatar.cc/150?img=29',
    role: 'guest',
    bio: '新入社員。プロジェクト管理を学習中。',
    status: 'away',
  },
];

// プロジェクトのモックデータ
export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'ECサイトリニューアル',
    description: '既存のECサイトを全面的にリニューアル。React/Next.jsを使用した最新のフロントエンド技術でユーザー体験を向上させます。',
    owner: mockUsers[0],
    members: [mockUsers[0], mockUsers[2], mockUsers[4], mockUsers[7]],
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-06-30'),
    status: 'active',
    progress: 65,
    tags: ['frontend', 'React', 'Next.js', 'e-commerce'],
  },
  {
    id: 'p2',
    name: 'モバイルアプリ開発',
    description: 'iOS/Android両対応のネイティブアプリ開発プロジェクト。React Nativeを採用し、効率的な開発を実現。',
    owner: mockUsers[1],
    members: [mockUsers[1], mockUsers[3], mockUsers[5]],
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-08-31'),
    status: 'active',
    progress: 45,
    tags: ['mobile', 'React Native', 'iOS', 'Android'],
  },
  {
    id: 'p3',
    name: '社内管理システム構築',
    description: '社内業務を効率化するための統合管理システムの構築。従業員管理、勤怠管理、経費精算などを一元化。',
    owner: mockUsers[0],
    members: [mockUsers[0], mockUsers[1], mockUsers[3], mockUsers[6], mockUsers[8]],
    startDate: new Date('2023-10-01'),
    endDate: new Date('2024-03-31'),
    status: 'active',
    progress: 80,
    tags: ['backend', 'Node.js', 'PostgreSQL', 'internal'],
  },
  {
    id: 'p4',
    name: 'AIチャットボット開発',
    description: 'カスタマーサポート向けのAIチャットボット開発。自然言語処理を活用した高度な対話機能を実装。',
    owner: mockUsers[1],
    members: [mockUsers[1], mockUsers[8], mockUsers[9]],
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-09-30'),
    status: 'planning',
    progress: 15,
    tags: ['AI', 'NLP', 'Python', 'machine-learning'],
  },
  {
    id: 'p5',
    name: 'マーケティングサイト制作',
    description: '新サービスのマーケティングサイト制作。SEO対策とデザイン性を重視した高品質なサイトを構築。',
    owner: mockUsers[4],
    members: [mockUsers[4], mockUsers[2], mockUsers[7]],
    startDate: new Date('2023-11-01'),
    endDate: new Date('2024-01-31'),
    status: 'completed',
    progress: 100,
    tags: ['marketing', 'SEO', 'design', 'frontend'],
  },
  {
    id: 'p6',
    name: 'データ分析基盤構築',
    description: 'ビッグデータ分析のための基盤構築。リアルタイムデータ処理とダッシュボード表示を実現。',
    owner: mockUsers[8],
    members: [mockUsers[8], mockUsers[1], mockUsers[6]],
    startDate: new Date('2024-01-10'),
    endDate: new Date('2024-07-31'),
    status: 'active',
    progress: 55,
    tags: ['data', 'analytics', 'AWS', 'bigquery'],
  },
  {
    id: 'p7',
    name: 'セキュリティ強化プロジェクト',
    description: '全社的なセキュリティ監査と脆弱性対策の実施。最新のセキュリティ基準に準拠した環境を構築。',
    owner: mockUsers[6],
    members: [mockUsers[6], mockUsers[1], mockUsers[3]],
    startDate: new Date('2024-02-15'),
    endDate: new Date('2024-05-31'),
    status: 'on-hold',
    progress: 30,
    tags: ['security', 'infrastructure', 'compliance'],
  },
  {
    id: 'p8',
    name: 'レガシーシステム移行',
    description: '旧システムから新システムへのデータ移行プロジェクト。ダウンタイムを最小限に抑えた移行計画を実施。',
    owner: mockUsers[0],
    members: [mockUsers[0], mockUsers[1], mockUsers[3], mockUsers[6]],
    startDate: new Date('2023-12-01'),
    endDate: new Date('2024-04-30'),
    status: 'active',
    progress: 70,
    tags: ['migration', 'database', 'backend'],
  },
  {
    id: 'p9',
    name: 'API v2.0 開発',
    description: 'RESTful API の次期バージョン開発。GraphQL対応とパフォーマンス改善を実施。',
    owner: mockUsers[3],
    members: [mockUsers[3], mockUsers[1], mockUsers[2]],
    startDate: new Date('2024-03-15'),
    endDate: new Date('2024-08-15'),
    status: 'planning',
    progress: 20,
    tags: ['API', 'GraphQL', 'backend', 'performance'],
  },
  {
    id: 'p10',
    name: 'デザインシステム構築',
    description: 'コンポーネントライブラリとデザインガイドラインの統一。Storybookを活用した管理体制を構築。',
    owner: mockUsers[4],
    members: [mockUsers[4], mockUsers[2], mockUsers[5]],
    startDate: new Date('2023-09-01'),
    endDate: new Date('2024-02-28'),
    status: 'completed',
    progress: 100,
    tags: ['design', 'frontend', 'component-library', 'Storybook'],
  },
];

// タスクのモックデータ
export const mockTasks: Task[] = [
  // ECサイトリニューアル（p1）のタスク
  {
    id: 't1',
    title: 'トップページのUIデザイン作成',
    description: 'レスポンシブ対応のトップページデザインをFigmaで作成',
    projectId: 'p1',
    assignee: mockUsers[4],
    dueDate: new Date('2024-02-15'),
    priority: 'high',
    status: 'completed',
    tags: ['design', 'UI'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 't2',
    title: '商品一覧ページの実装',
    description: 'フィルタリング機能とページネーションを含む商品一覧ページの実装',
    projectId: 'p1',
    assignee: mockUsers[2],
    dueDate: new Date('2024-03-10'),
    priority: 'high',
    status: 'in-progress',
    tags: ['frontend', 'React'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 't3',
    title: 'ショッピングカート機能の実装',
    description: 'カート追加・削除・数量変更機能の実装',
    projectId: 'p1',
    assignee: mockUsers[2],
    dueDate: new Date('2024-03-25'),
    priority: 'urgent',
    status: 'todo',
    tags: ['frontend', 'React'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 't4',
    title: '決済機能の統合',
    description: 'Stripe決済APIの統合とテスト',
    projectId: 'p1',
    assignee: mockUsers[7],
    dueDate: new Date('2024-04-05'),
    priority: 'high',
    status: 'todo',
    tags: ['backend', 'payment'],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 't5',
    title: 'SEO最適化の実装',
    description: 'メタタグ、構造化データ、サイトマップの実装',
    projectId: 'p1',
    assignee: mockUsers[2],
    dueDate: new Date('2024-05-15'),
    priority: 'medium',
    status: 'todo',
    tags: ['SEO', 'frontend'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },

  // モバイルアプリ開発（p2）のタスク
  {
    id: 't6',
    title: 'ログイン画面の実装',
    description: 'ソーシャルログイン対応のログイン画面実装',
    projectId: 'p2',
    assignee: mockUsers[1],
    dueDate: new Date('2024-03-20'),
    priority: 'high',
    status: 'completed',
    tags: ['mobile', 'authentication'],
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 't7',
    title: 'プッシュ通知機能の実装',
    description: 'Firebase Cloud Messagingを使用したプッシュ通知機能',
    projectId: 'p2',
    assignee: mockUsers[3],
    dueDate: new Date('2024-04-10'),
    priority: 'medium',
    status: 'in-progress',
    tags: ['mobile', 'notification'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-04-05'),
  },
  {
    id: 't8',
    title: 'オフライン対応の実装',
    description: 'ローカルストレージとデータ同期機能の実装',
    projectId: 'p2',
    assignee: mockUsers[1],
    dueDate: new Date('2024-05-15'),
    priority: 'medium',
    status: 'todo',
    tags: ['mobile', 'offline'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 't9',
    title: 'ユーザープロフィール画面の実装',
    description: 'プロフィール編集機能を含むユーザープロフィール画面',
    projectId: 'p2',
    assignee: mockUsers[5],
    dueDate: new Date('2024-04-25'),
    priority: 'high',
    status: 'in-progress',
    tags: ['mobile', 'UI'],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-04-20'),
  },

  // 社内管理システム構築（p3）のタスク
  {
    id: 't10',
    title: '従業員マスタ管理機能',
    description: '従業員情報のCRUD操作を行う管理画面の実装',
    projectId: 'p3',
    assignee: mockUsers[3],
    dueDate: new Date('2023-12-20'),
    priority: 'high',
    status: 'completed',
    tags: ['backend', 'CRUD'],
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2023-12-18'),
  },
  {
    id: 't11',
    title: '勤怠管理機能の実装',
    description: '出退勤記録、勤怠申請、承認ワークフローの実装',
    projectId: 'p3',
    assignee: mockUsers[1],
    dueDate: new Date('2024-01-31'),
    priority: 'urgent',
    status: 'completed',
    tags: ['backend', 'workflow'],
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: 't12',
    title: '経費精算機能の実装',
    description: '経費申請、承認フロー、レポート出力機能の実装',
    projectId: 'p3',
    assignee: mockUsers[8],
    dueDate: new Date('2024-02-28'),
    priority: 'high',
    status: 'in-progress',
    tags: ['backend', 'reporting'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 't13',
    title: 'ダッシュボードの実装',
    description: '各種統計情報を表示するダッシュボード画面の実装',
    projectId: 'p3',
    assignee: mockUsers[0],
    dueDate: new Date('2024-03-20'),
    priority: 'medium',
    status: 'in-progress',
    tags: ['frontend', 'dashboard'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 't14',
    title: 'モバイル対応の実装',
    description: 'スマートフォンからの勤怠入力対応',
    projectId: 'p3',
    assignee: mockUsers[6],
    dueDate: new Date('2024-03-31'),
    priority: 'medium',
    status: 'todo',
    tags: ['mobile', 'responsive'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },

  // AIチャットボット開発（p4）のタスク
  {
    id: 't15',
    title: '要件定義書の作成',
    description: 'チャットボットの機能要件と非機能要件の整理',
    projectId: 'p4',
    assignee: mockUsers[1],
    dueDate: new Date('2024-03-31'),
    priority: 'high',
    status: 'completed',
    tags: ['planning', 'documentation'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-28'),
  },
  {
    id: 't16',
    title: '自然言語処理モデルの選定',
    description: 'OpenAI GPT-4 vs Claude vs カスタムモデルの比較検討',
    projectId: 'p4',
    assignee: mockUsers[8],
    dueDate: new Date('2024-04-15'),
    priority: 'high',
    status: 'in-progress',
    tags: ['AI', 'research'],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 't17',
    title: 'トレーニングデータの準備',
    description: 'FAQデータとカスタマーサポート履歴の整理',
    projectId: 'p4',
    assignee: mockUsers[9],
    dueDate: new Date('2024-05-01'),
    priority: 'medium',
    status: 'todo',
    tags: ['data', 'preparation'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 't18',
    title: 'チャットUIの設計',
    description: 'ユーザーフレンドリーなチャットインターフェースの設計',
    projectId: 'p4',
    assignee: mockUsers[1],
    dueDate: new Date('2024-05-15'),
    priority: 'medium',
    status: 'todo',
    tags: ['design', 'UI'],
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },

  // マーケティングサイト制作（p5）のタスク
  {
    id: 't19',
    title: 'ランディングページの制作',
    description: 'コンバージョンを最適化したランディングページ',
    projectId: 'p5',
    assignee: mockUsers[4],
    dueDate: new Date('2023-12-15'),
    priority: 'high',
    status: 'completed',
    tags: ['design', 'marketing'],
    createdAt: new Date('2023-11-10'),
    updatedAt: new Date('2023-12-12'),
  },
  {
    id: 't20',
    title: 'ブログ機能の実装',
    description: 'CMSを使用したブログシステムの構築',
    projectId: 'p5',
    assignee: mockUsers[2],
    dueDate: new Date('2024-01-10'),
    priority: 'medium',
    status: 'completed',
    tags: ['CMS', 'frontend'],
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-08'),
  },

  // データ分析基盤構築（p6）のタスク
  {
    id: 't21',
    title: 'データウェアハウスの構築',
    description: 'BigQueryを使用したデータウェアハウスの設計と構築',
    projectId: 'p6',
    assignee: mockUsers[8],
    dueDate: new Date('2024-03-15'),
    priority: 'high',
    status: 'completed',
    tags: ['data', 'infrastructure'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: 't22',
    title: 'ETLパイプラインの構築',
    description: 'データ抽出・変換・ロードプロセスの自動化',
    projectId: 'p6',
    assignee: mockUsers[8],
    dueDate: new Date('2024-04-20'),
    priority: 'high',
    status: 'in-progress',
    tags: ['data', 'pipeline'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-04-15'),
  },
  {
    id: 't23',
    title: 'ダッシュボードの開発',
    description: 'Looker Studioを使用したダッシュボード作成',
    projectId: 'p6',
    assignee: mockUsers[1],
    dueDate: new Date('2024-05-30'),
    priority: 'medium',
    status: 'todo',
    tags: ['visualization', 'BI'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 't24',
    title: 'リアルタイム処理の実装',
    description: 'ストリーミングデータのリアルタイム処理',
    projectId: 'p6',
    assignee: mockUsers[6],
    dueDate: new Date('2024-06-30'),
    priority: 'medium',
    status: 'todo',
    tags: ['streaming', 'real-time'],
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-15'),
  },

  // セキュリティ強化プロジェクト（p7）のタスク
  {
    id: 't25',
    title: 'セキュリティ監査の実施',
    description: '全システムのセキュリティ診断とレポート作成',
    projectId: 'p7',
    assignee: mockUsers[6],
    dueDate: new Date('2024-03-31'),
    priority: 'urgent',
    status: 'completed',
    tags: ['security', 'audit'],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-28'),
  },
  {
    id: 't26',
    title: '脆弱性の修正',
    description: '発見された脆弱性の優先度付けと修正',
    projectId: 'p7',
    assignee: mockUsers[1],
    dueDate: new Date('2024-04-30'),
    priority: 'urgent',
    status: 'in-progress',
    tags: ['security', 'bug-fix'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 't27',
    title: 'WAFの導入',
    description: 'Web Application Firewallの設定と運用開始',
    projectId: 'p7',
    assignee: mockUsers[3],
    dueDate: new Date('2024-05-15'),
    priority: 'high',
    status: 'todo',
    tags: ['security', 'infrastructure'],
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },

  // レガシーシステム移行（p8）のタスク
  {
    id: 't28',
    title: 'データ移行計画の策定',
    description: '移行対象データの洗い出しと移行手順の作成',
    projectId: 'p8',
    assignee: mockUsers[0],
    dueDate: new Date('2024-01-15'),
    priority: 'high',
    status: 'completed',
    tags: ['planning', 'migration'],
    createdAt: new Date('2023-12-05'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 't29',
    title: 'テストデータ移行の実施',
    description: 'テスト環境でのデータ移行とバリデーション',
    projectId: 'p8',
    assignee: mockUsers[3],
    dueDate: new Date('2024-02-28'),
    priority: 'high',
    status: 'completed',
    tags: ['testing', 'migration'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 't30',
    title: '本番データ移行の実施',
    description: '本番環境への段階的なデータ移行',
    projectId: 'p8',
    assignee: mockUsers[6],
    dueDate: new Date('2024-04-15'),
    priority: 'urgent',
    status: 'in-progress',
    tags: ['production', 'migration'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 't31',
    title: '旧システムの廃止手続き',
    description: '旧システムのシャットダウンとデータアーカイブ',
    projectId: 'p8',
    assignee: mockUsers[1],
    dueDate: new Date('2024-04-30'),
    priority: 'medium',
    status: 'todo',
    tags: ['decommission'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },

  // API v2.0 開発（p9）のタスク
  {
    id: 't32',
    title: 'API設計書の作成',
    description: 'OpenAPI仕様に基づいたAPI設計書の作成',
    projectId: 'p9',
    assignee: mockUsers[3],
    dueDate: new Date('2024-04-15'),
    priority: 'high',
    status: 'in-progress',
    tags: ['API', 'documentation'],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 't33',
    title: 'GraphQLスキーマの設計',
    description: 'GraphQLスキーマとリゾルバーの設計',
    projectId: 'p9',
    assignee: mockUsers[1],
    dueDate: new Date('2024-05-01'),
    priority: 'high',
    status: 'todo',
    tags: ['GraphQL', 'backend'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 't34',
    title: 'パフォーマンステストの実施',
    description: '負荷テストとボトルネック分析',
    projectId: 'p9',
    assignee: mockUsers[2],
    dueDate: new Date('2024-06-15'),
    priority: 'medium',
    status: 'todo',
    tags: ['testing', 'performance'],
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },

  // デザインシステム構築（p10）のタスク
  {
    id: 't35',
    title: 'コンポーネントライブラリの構築',
    description: 'React/TypeScriptでの再利用可能なコンポーネント開発',
    projectId: 'p10',
    assignee: mockUsers[2],
    dueDate: new Date('2023-12-31'),
    priority: 'high',
    status: 'completed',
    tags: ['component', 'React'],
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2023-12-28'),
  },
  {
    id: 't36',
    title: 'Storybookのセットアップ',
    description: 'Storybookの導入とコンポーネントストーリーの作成',
    projectId: 'p10',
    assignee: mockUsers[4],
    dueDate: new Date('2024-01-31'),
    priority: 'high',
    status: 'completed',
    tags: ['Storybook', 'documentation'],
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: 't37',
    title: 'デザイントークンの定義',
    description: 'カラー、タイポグラフィ、スペーシングなどのトークン定義',
    projectId: 'p10',
    assignee: mockUsers[5],
    dueDate: new Date('2024-02-15'),
    priority: 'medium',
    status: 'completed',
    tags: ['design', 'tokens'],
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2024-02-12'),
  },

  // 追加のタスク（様々なプロジェクトに分散）
  {
    id: 't38',
    title: 'ユニットテストの作成',
    description: '主要機能のユニットテストカバレッジ80%を目指す',
    projectId: 'p1',
    assignee: mockUsers[5],
    dueDate: new Date('2024-05-30'),
    priority: 'medium',
    status: 'todo',
    tags: ['testing', 'quality'],
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 't39',
    title: 'パフォーマンス最適化',
    description: 'ページ読み込み速度の改善とLighthouseスコア向上',
    projectId: 'p1',
    assignee: mockUsers[2],
    dueDate: new Date('2024-06-15'),
    priority: 'low',
    status: 'todo',
    tags: ['performance', 'optimization'],
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-15'),
  },
  {
    id: 't40',
    title: 'アクセシビリティ対応',
    description: 'WCAG 2.1 AA準拠のアクセシビリティ実装',
    projectId: 'p2',
    assignee: mockUsers[5],
    dueDate: new Date('2024-06-30'),
    priority: 'medium',
    status: 'todo',
    tags: ['accessibility', 'a11y'],
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-01'),
  },
  {
    id: 't41',
    title: 'CI/CDパイプラインの構築',
    description: 'GitHub Actionsを使用した自動デプロイ環境の構築',
    projectId: 'p3',
    assignee: mockUsers[6],
    dueDate: new Date('2024-03-25'),
    priority: 'high',
    status: 'completed',
    tags: ['DevOps', 'automation'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 't42',
    title: 'ドキュメンテーションの整備',
    description: 'システムアーキテクチャとAPI仕様書の整備',
    projectId: 'p6',
    assignee: mockUsers[9],
    dueDate: new Date('2024-05-31'),
    priority: 'low',
    status: 'todo',
    tags: ['documentation'],
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 't43',
    title: 'エラーハンドリングの改善',
    description: 'ユーザーフレンドリーなエラーメッセージとロギング',
    projectId: 'p8',
    assignee: mockUsers[3],
    dueDate: new Date('2024-04-20'),
    priority: 'medium',
    status: 'in-progress',
    tags: ['error-handling', 'UX'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-04-15'),
  },
  {
    id: 't44',
    title: 'バックアップ体制の構築',
    description: '自動バックアップとリカバリー手順の整備',
    projectId: 'p7',
    assignee: mockUsers[6],
    dueDate: new Date('2024-05-30'),
    priority: 'high',
    status: 'todo',
    tags: ['backup', 'disaster-recovery'],
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 't45',
    title: 'ローディング状態の実装',
    description: 'スケルトンスクリーンとローディングインジケーターの実装',
    projectId: 'p2',
    assignee: mockUsers[1],
    dueDate: new Date('2024-05-01'),
    priority: 'low',
    status: 'todo',
    tags: ['UI', 'UX'],
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-15'),
  },
];

// チームメンバーのモックデータ
export const teamMembers = [
  { id: 1, name: '山田太郎', email: 'yamada@example.com', role: '管理者', taskCount: 12 },
  { id: 2, name: '佐藤花子', email: 'sato@example.com', role: '管理者', taskCount: 8 },
  { id: 3, name: '鈴木一郎', email: 'suzuki@example.com', role: 'メンバー', taskCount: 15 },
  { id: 4, name: '田中美咲', email: 'tanaka@example.com', role: 'メンバー', taskCount: 10 },
  { id: 5, name: '高橋健太', email: 'takahashi@example.com', role: 'メンバー', taskCount: 7 },
  { id: 6, name: '伊藤真理', email: 'ito@example.com', role: 'メンバー', taskCount: 9 },
  { id: 7, name: '渡辺直樹', email: 'watanabe@example.com', role: 'メンバー', taskCount: 11 },
  { id: 8, name: '中村さくら', email: 'nakamura@example.com', role: 'ゲスト', taskCount: 3 },
];

// カレンダーイベントのモックデータ
export const calendarEvents = [
  { id: 1, title: 'プロジェクトキックオフ', date: '2024-04-01', assignee: '山田太郎', type: 'ミーティング' as const },
  { id: 2, title: 'デザインレビュー', date: '2024-04-05', assignee: '高橋健太', type: 'ミーティング' as const },
  { id: 3, title: 'API実装完了', date: '2024-04-10', assignee: '田中美咲', type: '期限' as const },
  { id: 4, title: 'テスト実施', date: '2024-04-15', assignee: '伊藤真理', type: 'タスク' as const },
  { id: 5, title: 'スプリントレビュー', date: '2024-04-20', assignee: '佐藤花子', type: 'ミーティング' as const },
  { id: 6, title: 'リリース準備', date: '2024-04-25', assignee: '渡辺直樹', type: 'タスク' as const },
  { id: 7, title: '本番リリース', date: '2024-04-30', assignee: '山田太郎', type: '期限' as const },
];

// レポート統計データ
export const reportStats = {
  project: [
    { label: '総プロジェクト数', value: '10', change: 5, description: '全プロジェクト数' },
    { label: 'アクティブ', value: '6', change: 10, description: '進行中のプロジェクト' },
    { label: '完了', value: '2', change: 15, description: '完了したプロジェクト' },
    { label: '遅延', value: '1', change: -5, description: '遅延しているプロジェクト' },
  ],
  member: [
    { label: '総メンバー数', value: '8', change: 2, description: '全メンバー数' },
    { label: '平均タスク数', value: '9.4', change: 8, description: 'メンバーあたりの平均タスク数' },
    { label: '完了率', value: '78%', change: 12, description: 'タスク完了率' },
    { label: '生産性スコア', value: '85', change: 5, description: '生産性指標' },
  ],
  period: [
    { label: '今月のタスク', value: '42', change: 15, description: '今月作成されたタスク' },
    { label: '今月の完了', value: '35', change: 20, description: '今月完了したタスク' },
    { label: '達成率', value: '83%', change: 10, description: '今月の達成率' },
    { label: '平均完了時間', value: '2.5日', change: -8, description: 'タスクの平均完了時間' },
  ],
};

// レポート詳細データ
export const reportDetails = {
  project: [
    { id: 1, name: 'ECサイトリニューアル', taskCount: 15, completion: 65, status: '進行中' },
    { id: 2, name: 'モバイルアプリ開発', taskCount: 12, completion: 45, status: '進行中' },
    { id: 3, name: '社内管理システム構築', taskCount: 20, completion: 80, status: '進行中' },
    { id: 4, name: 'AIチャットボット開発', taskCount: 8, completion: 15, status: '未着手' },
    { id: 5, name: 'マーケティングサイト制作', taskCount: 10, completion: 100, status: '完了' },
  ],
  member: [
    { id: 1, name: '山田太郎', assignedTasks: 12, completedTasks: 10, productivity: '高' },
    { id: 2, name: '佐藤花子', assignedTasks: 8, completedTasks: 7, productivity: '高' },
    { id: 3, name: '鈴木一郎', assignedTasks: 15, completedTasks: 11, productivity: '中' },
    { id: 4, name: '田中美咲', assignedTasks: 10, completedTasks: 8, productivity: '高' },
    { id: 5, name: '高橋健太', assignedTasks: 7, completedTasks: 5, productivity: '中' },
  ],
  period: [
    { id: 1, month: '2024年1月', newTasks: 38, completedTasks: 32, achievementRate: 84 },
    { id: 2, month: '2024年2月', newTasks: 42, completedTasks: 35, achievementRate: 83 },
    { id: 3, month: '2024年3月', newTasks: 45, completedTasks: 38, achievementRate: 84 },
    { id: 4, month: '2024年4月', newTasks: 40, completedTasks: 30, achievementRate: 75 },
  ],
};

// 統計データを計算する関数
export const calculateStatistics = (): import('./types').Statistics => {
  const totalProjects = mockProjects.length;
  const activeProjects = mockProjects.filter(p => p.status === 'active').length;
  const completedProjects = mockProjects.filter(p => p.status === 'completed').length;
  const delayedProjects = mockProjects.filter(p => {
    const today = new Date();
    return p.endDate < today && p.status !== 'completed';
  }).length;

  const totalTasks = mockTasks.length;
  const todoTasks = mockTasks.filter(t => t.status === 'todo').length;
  const inProgressTasks = mockTasks.filter(t => t.status === 'in-progress').length;
  const completedTasks = mockTasks.filter(t => t.status === 'completed').length;

  return {
    totalProjects,
    activeProjects,
    completedProjects,
    delayedProjects,
    totalTasks,
    todoTasks,
    inProgressTasks,
    completedTasks,
  };
};
